71 planilhas graficos custo qualidade
fga-eps-mds/2021.1-PC-GO1 pull request #87
Opened 2021-09-11 05:03 UTC by bielrossi15

## Descrição 

Foram criados documentos de risco, custo e qualidade do projeto para seguir a metodologia aplicada e ter o controle sobre essas variáveis.

## Issue Correspondente
closes #71 

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

2021-09-11 19:25 UTC, PauloVitorRocha requested changes
Revisar o que foi comentado no codigo

2021-09-11 19:25 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +
Representar os custos em reais por meio da notação R$1.000,00

2021-09-11 19:25 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +A equipe teve o gasto 44918.30 reais, porém não foi gasto a mais apenas de 17727.27`(44918.30(Custo Real) - 27272.72(Valor Planejado))`. Foi gasto na realidade
Não compreendi o que foi escrito aqui
```suggestion
A equipe teve o gasto R$44.918,30, porém não foi gasto a mais apenas de R$17.727,27`(44.918,30(Custo Real) - 27.272,72(Valor Planejado))`. Foi gasto na realidade
```

2021-09-11 19:29 UTC, PauloVitorRocha requested changes

2021-09-11 19:29 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +- CPI: Cost Performance Index (Índice de Desempenho de Custos) =  `Custo Real/Valor agregado`, quanto mais perto de 1 melhor.
explicar o que significa esses índices e como eles agregam ao valor do produto

2021-09-11 19:29 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +## Valor Planejado versus Valor Agregado
Explicar o que significa esse gráfico

2021-09-11 20:00 UTC, PauloVitorRocha requested changes

2021-09-11 20:03 UTC, PauloVitorRocha requested changes

2021-09-11 20:03 UTC, PauloVitorRocha commented on docs/metodologia/metricas_qualidade.md
> +<h1 style="text-align: center">Métricas de Qualidade</h1>
Nenhum dos outros títulos está alinhado no centro.

2021-09-11 20:22 UTC, bielrossi15 commented on docs/metodologia/metricas_qualidade.md
> +<h1 style="text-align: center">Métricas de Qualidade</h1>
retirado.

2021-09-12 00:45 UTC, PauloVitorRocha requested changes
Melhorou bastante a qualidade do documento, os índices estão devidamente explicados e os gráficos também. Porém acredito que ainda tenha que fazer apenas um pequeno ajuste na formatação dos valores em R$

2021-09-12 00:45 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +`Valor Planejado = 0,222 * R$100.000 = 22200`
```suggestion
`Valor Planejado = 0,222 * R$100.000 = R$22.200`
```
acredito que esse valor seja em reais correto?

2021-09-12 00:45 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +`Valor Agregado = 0,05 * R$100.000 = 5000 `
```suggestion
`Valor Agregado = 0,05 * R$100.000 = R$5.000 `
```

2021-09-12 00:45 UTC, PauloVitorRocha commented on docs/metodologia/custo.md
> +`SPV = 5000 - 22200 = -17200`
```suggestion
`SPV = 5000 - 22200 = -R$17.200`
```

2021-09-12 01:30 UTC, darmsDD commented on docs/metodologia/custo.md
> +- CPI: Cost Performance Index (Índice de Desempenho de Custos) =  `Custo Real/Valor agregado`, quanto mais perto de 1 melhor.
Documento foi remodelado para explicar melhor essas métricas.

2021-09-12 01:45 UTC, PauloVitorRocha approved these changes
Bom trabalho Ivan, continue assim!

2021-09-12 01:45 UTC, merged